### ISSUE TITLE
Fix Windows support

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-plugin-edge-handlers#36]
From the PR at https://github.com/netlify/netlify-plugin-edge-handlers/pull/33, it appears that there might be some issues when running this plugin on Windows (apparently due to file path delimiters difference). Specifically the CI tests [fail on Windows](https://github.com/netlify/netlify-plugin-edge-handlers/pull/33/checks?check_run_id=1102569449).

```
┌─────────────────────────────┐
│        Netlify Build        │
└─────────────────────────────┘

> Version
  @netlify/build 3.3.5

> Flags
  cwd: 'D:\a\netlify-plugin-handler\netlify-plugin-handler\test/../integration-test'

> Current directory
  D:\a\netlify-plugin-handler\netlify-plugin-handler\integration-test

> Config file
  D:\a\netlify-plugin-handler\netlify-plugin-handler\integration-test\netlify.toml

> Context
  production

> Loading plugins
   - ../@1.0.0 from netlify.toml

┌─────────────────────────────────┐
│ 1. onPostBuild command from ../ │
└─────────────────────────────────┘

┌─────────────────────────────┐
│ Plugin "../" internal error │
└─────────────────────────────┘

  Error message
  Error: Could not resolve D:a
  etlify-plugin-handler
  etlify-plugin-handlerintegration-testedge-handlersexample module. Please install this locally

  Plugin details
  Package:        ../
  Version:        1.0.0

  Error location
  In "onPostBuild" event in "../" from netlify.toml
      at Object.onwarn (D:\a\netlify-plugin-handler\netlify-plugin-handler\src\index.js:18:335)
      at Object.onwarn (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:19023:20)
      at ModuleLoader.handleResolveId (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:17904:26)
      at async Promise.all (index 0)
      at async ModuleLoader.fetchStaticDependencies (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:17892:34)
      at async Promise.all (index 0)
      at async ModuleLoader.fetchModule (D:\a\netlify-plugin-handler\netlify-plugin-handler\node_modules\rollup\dist\shared\rollup.js:17869:9)
      at async Promise.all (index 0)

  Error properties
  {
    watchFiles: [
      'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\handlers-mEve5D\\__netlifyMain.ts'
    ]
  }

  Resolved config
  build:
    base: 'D:\a\netlify-plugin-handler\netlify-plugin-handler\integration-test'
    ignore: 'false'
  plugins:
    - inputs: {}
      origin: config
      package: ../
  redirects:
    - edge_function: hello-world
      force: true
      from: /
      status: 200
```

This is unclear whether this is a problem with the source code or the test code, and requires additional investigation.
This fails in Netlify Build tests too, which is not using the same test code, so I am assuming this is probably source code related.

Note: we need Windows support due to Windows users running `netlify build` on the CLI.

**Comment by shortdiv** [comment]
Is this blocking #33? Should we wait to triage this before merging that PR?

**Comment by ehmicky** [comment]
Do you mean this due to Windows tests failing in CI (i.e. showing up in PRs)?
I think if we don't find a solution to Windows support soon, we probably should disable Windows tests in CI.

**Comment by ehmicky** [comment]
Done at #60.
